"use client";
import * as XLSX from "xlsx";
import { BarChart3, Boxes, Download, ReceiptText, TrendingUp, Utensils } from "lucide-react";

type Fila={nombre:string;valor:number;extra?:number};
type Props={ventasDiarias:Fila[];productos:Fila[];mesas:Fila[];stock:Fila[];gastos:Fila[];totalVentas:number;totalPedidos:number;ticketPromedio:number};
export function ReportesDashboard(props:Props){const exportar=()=>{const wb=XLSX.utils.book_new();const tabs:[string,Fila[]][]=[["Ventas",props.ventasDiarias],["Productos",props.productos],["Mesas",props.mesas],["Stock",props.stock],["Gastos",props.gastos]];for(const [nombre,filas] of tabs)XLSX.utils.book_append_sheet(wb,XLSX.utils.json_to_sheet(filas.map(f=>({Nombre:f.nombre,Valor:f.valor,Adicional:f.extra??""}))),nombre);XLSX.writeFile(wb,`reporte-restomanager-${new Date().toISOString().slice(0,10)}.xlsx`);};const maxVentas=Math.max(1,...props.ventasDiarias.map(v=>v.valor));return <div className="space-y-7"><header className="flex flex-wrap items-end gap-4"><div><p className="text-xs uppercase tracking-[.2em] font-black text-[#E63946]">Últimos 30 días</p><h1 className="text-3xl font-black text-slate-900">Pulso del restaurante</h1><p className="text-sm text-slate-500">Ventas, demanda y operación en una sola lectura.</p></div><button onClick={exportar} className="ml-auto px-4 py-3 rounded-xl bg-[#1D3557] text-white text-sm font-black flex gap-2"><Download className="w-4 h-4"/>Exportar Excel</button></header><section className="grid sm:grid-cols-3 border-y border-slate-200 divide-y sm:divide-y-0 sm:divide-x"><Kpi icon={TrendingUp} label="Ventas" value={`$ ${Math.round(props.totalVentas).toLocaleString("es-CO")}`}/><Kpi icon={ReceiptText} label="Pedidos" value={String(props.totalPedidos)}/><Kpi icon={BarChart3} label="Ticket promedio" value={`$ ${Math.round(props.ticketPromedio).toLocaleString("es-CO")}`}/></section><section className="grid lg:grid-cols-[1.35fr_.65fr] gap-6"><div className="bg-white border rounded-3xl p-6"><h2 className="font-black">Ritmo de ventas</h2><div className="h-60 flex items-end gap-1 mt-6">{props.ventasDiarias.map((d,i)=><div key={i} className="flex-1 min-w-1 group relative"><div className="bg-[#457B9D] rounded-t hover:bg-[#E63946] transition" style={{height:`${Math.max(3,d.valor/maxVentas*220)}px`}}/><span className="hidden group-hover:block absolute -top-8 left-1/2 -translate-x-1/2 bg-slate-900 text-white text-[9px] p-1 rounded whitespace-nowrap">$ {Math.round(d.valor).toLocaleString("es-CO")}</span></div>)}</div></div><Ranking title="Productos más vendidos" icon={Utensils} rows={props.productos} suffix="uds."/></section><section className="grid lg:grid-cols-3 gap-5"><Ranking title="Mesas con más movimiento" icon={BarChart3} rows={props.mesas} suffix="pedidos"/><Ranking title="Stock crítico" icon={Boxes} rows={props.stock} suffix="disponible" danger/><Ranking title="Gastos por categoría" icon={ReceiptText} rows={props.gastos} suffix="COP"/></section></div>}
function Kpi({icon:Icon,label,value}:{icon:typeof TrendingUp;label:string;value:string}){return <div className="py-5 sm:px-6 first:pl-0"><Icon className="w-5 h-5 text-[#E63946]"/><p className="text-xs text-slate-500 mt-3">{label}</p><p className="text-2xl font-black">{value}</p></div>}
function Ranking({title,icon:Icon,rows,suffix,danger}:{title:string;icon:typeof TrendingUp;rows:Fila[];suffix:string;danger?:boolean}){const max=Math.max(1,...rows.map(r=>r.valor));return <div className="bg-white border rounded-3xl p-5"><div className="flex items-center gap-2"><Icon className="w-5 h-5 text-[#E63946]"/><h2 className="font-black">{title}</h2></div><div className="mt-5 space-y-4">{rows.slice(0,7).map((r,i)=><div key={`${r.nombre}-${i}`}><div className="flex justify-between text-xs"><span className="font-bold truncate pr-3">{r.nombre}</span><span>{Math.round(r.valor).toLocaleString("es-CO")} {suffix}</span></div><div className="h-1.5 bg-slate-100 rounded mt-1"><div className={`h-full rounded ${danger&&r.extra===1?"bg-rose-500":"bg-[#F4A261]"}`} style={{width:`${r.valor/max*100}%`}}/></div></div>)}{!rows.length&&<p className="text-sm text-slate-400">Sin datos para el período.</p>}</div></div>}
