"use client";

import { useState, useTransition } from "react";
import { useRouter } from "next/navigation";
import * as XLSX from "xlsx";
import { TipoMovimientoCuenta } from "@prisma/client";
import { ArrowDownRight, ArrowUpRight, Building2, CircleDollarSign, FileSpreadsheet, Plus, ReceiptText, Trash2, TrendingUp, UserRound, WalletCards } from "lucide-react";
import { Button } from "@/components/ui/button";
import { Modal } from "@/components/ui/modal";
import { crearCategoriaGastoAction, eliminarClienteAction, eliminarGastoAction, eliminarProveedorAction, guardarClienteAction, guardarGastoAction, guardarProveedorAction, importarEntidadesAction, registrarMovimientoCuentaAction } from "@/features/finanzas/actions";
import type { ActionResult } from "@/features/menu/actions";

type Movimiento={id:string;tipo:TipoMovimientoCuenta;monto:number;concepto:string;createdAt:string};
type Cliente={id:string;nombre:string;email:string|null;telefono:string|null;documento:string|null;direccion:string|null;saldoCuentaCorriente:number;descuentoFijo:number|null;movimientosCuenta:Movimiento[];_count:{pedidos:number}};
type Proveedor={id:string;nombre:string;contacto:string|null;telefono:string|null;email:string|null;direccion:string|null;categoria:string|null;saldoCuentaCorriente:number;movimientosCuenta:Movimiento[];_count:{gastos:number}};
type Categoria={id:string;nombre:string};
type Gasto={id:string;categoriaId:string;proveedorId:string|null;descripcion:string;monto:number;fecha:string;pagado:boolean;fechaVencimiento:string|null;categoria:Categoria;proveedor:{nombre:string}|null};
type Props={canManageFinances:boolean;clientes:Cliente[];proveedores:Proveedor[];categorias:Categoria[];gastos:Gasto[];ingresosMes:number;gastosMes:number};
type ClienteForm={nombre:string;email:string;telefono:string;documento:string;direccion:string;descuentoFijo:number};
type ProveedorForm={nombre:string;contacto:string;telefono:string;email:string;direccion:string;categoria:string};
const clienteVacio:ClienteForm={nombre:"",email:"",telefono:"",documento:"",direccion:"",descuentoFijo:0};
const proveedorVacio:ProveedorForm={nombre:"",contacto:"",telefono:"",email:"",direccion:"",categoria:""};

export function FinanzasManager({canManageFinances,clientes,proveedores,categorias,gastos,ingresosMes,gastosMes}:Props){
 const router=useRouter(); const [tab,setTab]=useState<"clientes"|"proveedores"|"gastos"|"resultados">("clientes"); const [pending,startTransition]=useTransition();
 const [mensaje,setMensaje]=useState<{ok:boolean;text:string}|null>(null); const [clienteEditor,setClienteEditor]=useState<{id:string|null;form:ClienteForm}|null>(null); const [proveedorEditor,setProveedorEditor]=useState<{id:string|null;form:ProveedorForm}|null>(null);
 const [cuenta,setCuenta]=useState<{entidad:"CLIENTE"|"PROVEEDOR";id:string;nombre:string}|null>(null); const [tipoMovimiento,setTipoMovimiento]=useState<TipoMovimientoCuenta>(TipoMovimientoCuenta.CARGO); const [montoMovimiento,setMontoMovimiento]=useState(0); const [concepto,setConcepto]=useState("");
 const [gastoEditor,setGastoEditor]=useState<{id:string|null;form:{categoriaId:string;proveedorId:string;descripcion:string;monto:number;fecha:string;pagado:boolean;fechaVencimiento:string}}|null>(null); const [nuevaCategoria,setNuevaCategoria]=useState("");
 const money=(n:number)=>`$ ${Math.round(n).toLocaleString("es-CO")}`; const resultado=ingresosMes-gastosMes; const vencidos=gastos.filter(g=>!g.pagado&&g.fechaVencimiento&&new Date(g.fechaVencimiento)<new Date());
 const ejecutar=(accion:()=>Promise<ActionResult>)=>startTransition(async()=>{setMensaje(null);const r=await accion();setMensaje({ok:r.success,text:r.message??r.error??"Operación finalizada"});if(r.success){setClienteEditor(null);setProveedorEditor(null);setCuenta(null);setGastoEditor(null);router.refresh();}});
 const importar=async(tipo:"CLIENTES"|"PROVEEDORES",file:File)=>{const data=await file.arrayBuffer();const book=XLSX.read(data);const sheet=book.Sheets[book.SheetNames[0]];const filas=XLSX.utils.sheet_to_json<Record<string,string|number|boolean|null>>(sheet,{defval:""});ejecutar(()=>importarEntidadesAction(tipo,filas));};
 return <div className="space-y-6">
  <header><p className="text-xs font-black uppercase tracking-[.18em] text-[#E63946]">Fase 5 · Administración</p><h1 className="text-3xl font-black text-slate-900">{canManageFinances ? "Relaciones y finanzas" : "Clientes"}</h1><p className="text-sm text-slate-500 mt-1">Clientes, proveedores, obligaciones y resultado del negocio en un solo lugar.</p></header>
  {mensaje&&<div className={`px-4 py-3 rounded-xl text-sm font-bold ${mensaje.ok?"bg-emerald-50 text-emerald-700":"bg-rose-50 text-rose-700"}`}>{mensaje.text}</div>}
  {canManageFinances && <section className="grid grid-cols-2 lg:grid-cols-4 gap-3">{[["Ingresos del mes",money(ingresosMes),TrendingUp,"text-emerald-600"],["Gastos del mes",money(gastosMes),ReceiptText,"text-rose-600"],["Resultado",money(resultado),CircleDollarSign,resultado>=0?"text-sky-600":"text-rose-600"],["Vencidos",vencidos.length,WalletCards,"text-amber-600"]].map(([l,v,I,c])=>{const Icon=I as typeof TrendingUp;return <div key={String(l)} className="bg-white border border-slate-200 rounded-2xl p-4"><Icon className={`w-5 h-5 ${c}`} /><p className="text-xs text-slate-500 mt-3">{String(l)}</p><p className="text-xl font-black text-slate-900">{String(v)}</p></div>})}</section>}
  <nav className="flex border-b border-slate-200 overflow-x-auto">{[["clientes","Clientes",UserRound],["proveedores","Proveedores",Building2],["gastos","Gastos",ReceiptText],["resultados","Resultados",TrendingUp]].filter(([id]) => canManageFinances || id === "clientes").map(([id,l,I])=>{const Icon=I as typeof UserRound;return <button key={String(id)} onClick={()=>setTab(id as typeof tab)} className={`px-4 py-3 border-b-2 text-sm font-bold flex gap-2 items-center ${tab===id?"border-[#E63946] text-[#E63946]":"border-transparent text-slate-500"}`}><Icon className="w-4 h-4" />{String(l)}</button>})}</nav>

  {tab==="clientes"&&<EntitySection title="Clientes" onNew={()=>setClienteEditor({id:null,form:{...clienteVacio}})} onImport={(f)=>importar("CLIENTES",f)}>{clientes.map(c=><EntityRow key={c.id} title={c.nombre} subtitle={[c.documento,c.telefono,c.email].filter(Boolean).join(" · ")} balance={c.saldoCuentaCorriente} badge={c.descuentoFijo?`${c.descuentoFijo}% descuento`:undefined} onEdit={()=>setClienteEditor({id:c.id,form:{nombre:c.nombre,email:c.email??"",telefono:c.telefono??"",documento:c.documento??"",direccion:c.direccion??"",descuentoFijo:c.descuentoFijo??0}})} onAccount={()=>setCuenta({entidad:"CLIENTE",id:c.id,nombre:c.nombre})} onDelete={()=>ejecutar(()=>eliminarClienteAction(c.id))}/>)}</EntitySection>}
  {tab==="proveedores"&&<EntitySection title="Proveedores" onNew={()=>setProveedorEditor({id:null,form:{...proveedorVacio}})} onImport={(f)=>importar("PROVEEDORES",f)}>{proveedores.map(p=><EntityRow key={p.id} title={p.nombre} subtitle={[p.categoria,p.contacto,p.telefono].filter(Boolean).join(" · ")} balance={p.saldoCuentaCorriente} onEdit={()=>setProveedorEditor({id:p.id,form:{nombre:p.nombre,contacto:p.contacto??"",telefono:p.telefono??"",email:p.email??"",direccion:p.direccion??"",categoria:p.categoria??""}})} onAccount={()=>setCuenta({entidad:"PROVEEDOR",id:p.id,nombre:p.nombre})} onDelete={()=>ejecutar(()=>eliminarProveedorAction(p.id))}/>)}</EntitySection>}
  {tab==="gastos"&&<section className="bg-white border border-slate-200 rounded-2xl overflow-hidden"><div className="p-4 flex flex-wrap gap-2 items-center border-b"><h2 className="font-black mr-auto">Registro de gastos</h2><input value={nuevaCategoria} onChange={e=>setNuevaCategoria(e.target.value)} placeholder="Nueva categoría" className="h-9 px-3 rounded-lg border text-xs"/><Button size="sm" variant="outline" onClick={()=>ejecutar(()=>crearCategoriaGastoAction(nuevaCategoria))}>Crear categoría</Button><Button size="sm" onClick={()=>setGastoEditor({id:null,form:{categoriaId:categorias[0]?.id??"",proveedorId:"",descripcion:"",monto:0,fecha:new Date().toISOString().slice(0,10),pagado:true,fechaVencimiento:""}})}><Plus className="w-4 h-4"/> Gasto</Button></div><div className="divide-y">{gastos.map(g=><div key={g.id} className={`p-4 flex items-center gap-3 ${!g.pagado&&g.fechaVencimiento&&new Date(g.fechaVencimiento)<new Date()?"bg-rose-50":""}`}><div><p className="font-bold text-sm">{g.descripcion}</p><p className="text-xs text-slate-500">{g.categoria.nombre}{g.proveedor?` · ${g.proveedor.nombre}`:""} · {new Date(g.fecha).toLocaleDateString("es-CO")}</p></div><div className="ml-auto text-right"><p className="font-black">{money(g.monto)}</p><p className={`text-[10px] font-bold ${g.pagado?"text-emerald-600":"text-amber-600"}`}>{g.pagado?"PAGADO":"PENDIENTE"}</p></div><button onClick={()=>setGastoEditor({id:g.id,form:{categoriaId:g.categoriaId,proveedorId:g.proveedorId??"",descripcion:g.descripcion,monto:g.monto,fecha:g.fecha.slice(0,10),pagado:g.pagado,fechaVencimiento:g.fechaVencimiento?.slice(0,10)??""}})} className="text-xs font-bold text-sky-600">Editar</button><button onClick={()=>ejecutar(()=>eliminarGastoAction(g.id))} className="text-rose-500"><Trash2 className="w-4 h-4"/></button></div>)}</div></section>}
  {tab==="resultados"&&<section className="grid lg:grid-cols-[1.2fr_.8fr] gap-5"><div className="bg-slate-900 text-white rounded-3xl p-7"><p className="text-xs uppercase tracking-widest text-slate-400">Estado de resultados · mes actual</p><div className="mt-8 space-y-5"><ResultRow label="Ingresos por ventas" value={ingresosMes} positive/><ResultRow label="Gastos operativos" value={gastosMes}/><div className="border-t border-white/15 pt-5 flex justify-between items-end"><span className="font-black">Resultado neto</span><span className={`text-3xl font-black ${resultado>=0?"text-emerald-400":"text-rose-400"}`}>{money(resultado)}</span></div></div></div><div className="bg-white border rounded-3xl p-6"><h3 className="font-black">Gastos por categoría</h3><div className="mt-5 space-y-3">{categorias.map(c=>{const total=gastos.filter(g=>g.categoriaId===c.id&&new Date(g.fecha).getMonth()===new Date().getMonth()).reduce((s,g)=>s+g.monto,0);return <div key={c.id}><div className="flex justify-between text-xs"><span>{c.nombre}</span><b>{money(total)}</b></div><div className="h-1.5 bg-slate-100 rounded mt-1"><div className="h-full bg-[#E63946] rounded" style={{width:`${gastosMes?Math.min(100,total/gastosMes*100):0}%`}}/></div></div>})}</div></div></section>}

  {clienteEditor&&<EditorModal title={clienteEditor.id?"Editar cliente":"Nuevo cliente"} form={clienteEditor.form} setForm={form=>setClienteEditor({...clienteEditor,form})} fields={[['nombre','Nombre'],['documento','Documento'],['email','Email'],['telefono','Teléfono'],['direccion','Dirección'],['descuentoFijo','Descuento %']]} pending={pending} onClose={()=>setClienteEditor(null)} onSave={()=>ejecutar(()=>guardarClienteAction(clienteEditor.id,clienteEditor.form))}/>} 
  {proveedorEditor&&<EditorModal title={proveedorEditor.id?"Editar proveedor":"Nuevo proveedor"} form={proveedorEditor.form} setForm={form=>setProveedorEditor({...proveedorEditor,form})} fields={[['nombre','Nombre'],['categoria','Categoría'],['contacto','Contacto'],['email','Email'],['telefono','Teléfono'],['direccion','Dirección']]} pending={pending} onClose={()=>setProveedorEditor(null)} onSave={()=>ejecutar(()=>guardarProveedorAction(proveedorEditor.id,proveedorEditor.form))}/>} 
  {cuenta&&<Modal isOpen onClose={()=>setCuenta(null)} title={`Cuenta corriente · ${cuenta.nombre}`} description="Cargo aumenta la deuda; abono reduce el saldo."><div className="grid grid-cols-2 gap-2"><button onClick={()=>setTipoMovimiento(TipoMovimientoCuenta.CARGO)} className={`p-2 rounded-lg border text-sm font-bold ${tipoMovimiento==="CARGO"?"bg-rose-50 border-rose-300":""}`}>Cargo</button><button onClick={()=>setTipoMovimiento(TipoMovimientoCuenta.ABONO)} className={`p-2 rounded-lg border text-sm font-bold ${tipoMovimiento==="ABONO"?"bg-emerald-50 border-emerald-300":""}`}>Abono</button></div><input type="number" value={montoMovimiento||""} onChange={e=>setMontoMovimiento(Number(e.target.value))} placeholder="Monto" className="w-full mt-3 p-2 border rounded-xl"/><input value={concepto} onChange={e=>setConcepto(e.target.value)} placeholder="Concepto" className="w-full mt-3 p-2 border rounded-xl"/><Button className="w-full mt-4" isLoading={pending} onClick={()=>ejecutar(()=>registrarMovimientoCuentaAction(cuenta.entidad,{entidadId:cuenta.id,tipo:tipoMovimiento,monto:montoMovimiento,concepto}))}>Registrar</Button></Modal>}
  {gastoEditor&&<Modal isOpen onClose={()=>setGastoEditor(null)} title={gastoEditor.id?"Editar gasto":"Nuevo gasto"}><div className="grid grid-cols-2 gap-3"><select value={gastoEditor.form.categoriaId} onChange={e=>setGastoEditor({...gastoEditor,form:{...gastoEditor.form,categoriaId:e.target.value}})} className="p-2 border rounded-xl"><option value="">Categoría</option>{categorias.map(c=><option key={c.id} value={c.id}>{c.nombre}</option>)}</select><select value={gastoEditor.form.proveedorId} onChange={e=>setGastoEditor({...gastoEditor,form:{...gastoEditor.form,proveedorId:e.target.value}})} className="p-2 border rounded-xl"><option value="">Sin proveedor</option>{proveedores.map(p=><option key={p.id} value={p.id}>{p.nombre}</option>)}</select><input value={gastoEditor.form.descripcion} onChange={e=>setGastoEditor({...gastoEditor,form:{...gastoEditor.form,descripcion:e.target.value}})} placeholder="Descripción" className="col-span-2 p-2 border rounded-xl"/><input type="number" value={gastoEditor.form.monto||""} onChange={e=>setGastoEditor({...gastoEditor,form:{...gastoEditor.form,monto:Number(e.target.value)}})} placeholder="Monto" className="p-2 border rounded-xl"/><input type="date" value={gastoEditor.form.fecha} onChange={e=>setGastoEditor({...gastoEditor,form:{...gastoEditor.form,fecha:e.target.value}})} className="p-2 border rounded-xl"/><input type="date" value={gastoEditor.form.fechaVencimiento} onChange={e=>setGastoEditor({...gastoEditor,form:{...gastoEditor.form,fechaVencimiento:e.target.value}})} className="p-2 border rounded-xl"/><label className="flex items-center gap-2 text-sm"><input type="checkbox" checked={gastoEditor.form.pagado} onChange={e=>setGastoEditor({...gastoEditor,form:{...gastoEditor.form,pagado:e.target.checked}})}/> Pagado</label></div><Button className="w-full mt-4" isLoading={pending} onClick={()=>ejecutar(()=>guardarGastoAction(gastoEditor.id,gastoEditor.form))}>Guardar gasto</Button></Modal>}
 </div>
}

function EntitySection({title,onNew,onImport,children}:{title:string;onNew:()=>void;onImport:(f:File)=>void;children:React.ReactNode}){return <section className="bg-white border rounded-2xl overflow-hidden"><div className="p-4 border-b flex items-center"><h2 className="font-black">{title}</h2><div className="ml-auto flex gap-2"><label className="h-8 px-3 rounded-lg border text-xs font-bold flex items-center gap-1.5 cursor-pointer"><FileSpreadsheet className="w-4 h-4"/> Importar<input type="file" accept=".xlsx,.xls,.csv" className="hidden" onChange={e=>e.target.files?.[0]&&onImport(e.target.files[0])}/></label><Button size="sm" onClick={onNew}><Plus className="w-4 h-4"/> Nuevo</Button></div></div><div className="divide-y">{children}</div></section>}
function EntityRow({title,subtitle,balance,badge,onEdit,onAccount,onDelete}:{title:string;subtitle:string;balance:number;badge?:string;onEdit:()=>void;onAccount:()=>void;onDelete:()=>void}){return <div className="p-4 flex items-center gap-3"><div><p className="font-bold text-sm">{title}</p><p className="text-xs text-slate-500">{subtitle||"Sin datos de contacto"}</p>{badge&&<span className="text-[10px] font-bold text-emerald-700">{badge}</span>}</div><div className="ml-auto text-right"><p className={`font-black ${balance>0?"text-rose-600":"text-slate-700"}`}>{`$ ${Math.round(balance).toLocaleString("es-CO")}`}</p><p className="text-[10px] text-slate-400">saldo corriente</p></div><button onClick={onAccount} className="text-xs font-bold text-amber-600">Cuenta</button><button onClick={onEdit} className="text-xs font-bold text-sky-600">Editar</button><button onClick={onDelete} className="text-rose-500"><Trash2 className="w-4 h-4"/></button></div>}
function ResultRow({label,value,positive}:{label:string;value:number;positive?:boolean}){return <div className="flex justify-between"><span className="text-slate-300">{label}</span><span className={`font-black flex items-center gap-1 ${positive?"text-emerald-400":"text-rose-400"}`}>{positive?<ArrowUpRight className="w-4 h-4"/>:<ArrowDownRight className="w-4 h-4"/>}$ {Math.round(value).toLocaleString("es-CO")}</span></div>}
function EditorModal<T extends Record<string,string|number>>({title,form,setForm,fields,pending,onClose,onSave}:{title:string;form:T;setForm:(f:T)=>void;fields:Array<[keyof T,string]>;pending:boolean;onClose:()=>void;onSave:()=>void}){return <Modal isOpen onClose={onClose} title={title}><div className="grid grid-cols-2 gap-3">{fields.map(([key,label])=><label key={String(key)} className="text-xs font-bold text-slate-600">{label}<input type={typeof form[key]==="number"?"number":"text"} value={form[key]} onChange={e=>setForm({...form,[key]:typeof form[key]==="number"?Number(e.target.value):e.target.value})} className="block w-full mt-1 p-2 border rounded-xl font-normal"/></label>)}</div><div className="flex justify-end gap-2 mt-4"><Button variant="outline" onClick={onClose}>Cancelar</Button><Button isLoading={pending} onClick={onSave}>Guardar</Button></div></Modal>}
