"use server";

import { revalidatePath } from "next/cache";
import { Prisma, Rol, TipoMovimientoCuenta } from "@prisma/client";
import { prisma } from "@/lib/prisma";
import { requireAuthRoles } from "@/lib/auth-helpers";
import type { ActionResult } from "@/features/menu/actions";
import { categoriaGastoSchema, clienteSchema, gastoSchema, movimientoCuentaSchema, proveedorSchema, type ClienteInput, type GastoInput, type MovimientoCuentaInput, type ProveedorInput } from "@/schemas/finanzas.schema";

const SOLO_ADMIN = [Rol.ADMIN];
const GESTION_CLIENTES = [Rol.ADMIN, Rol.CAJERO];
const money = (n: number) => new Prisma.Decimal(n.toFixed(2));
const nullable = (v?: string) => v?.trim() || null;
const refresh = () => { revalidatePath("/admin/finanzas"); revalidatePath("/pos"); revalidatePath("/caja"); };

export async function guardarClienteAction(id: string | null, data: ClienteInput): Promise<ActionResult> {
  try { await requireAuthRoles(GESTION_CLIENTES); const p=clienteSchema.safeParse(data); if(!p.success)return{success:false,error:p.error.issues[0]?.message}; const payload={...p.data,email:nullable(p.data.email),telefono:nullable(p.data.telefono),documento:nullable(p.data.documento),direccion:nullable(p.data.direccion),descuentoFijo:p.data.descuentoFijo===undefined?null:money(p.data.descuentoFijo)}; if(id)await prisma.cliente.update({where:{id},data:payload});else await prisma.cliente.create({data:payload}); refresh(); return{success:true,message:id?"Cliente actualizado":"Cliente creado"}; } catch(e){return{success:false,error:e instanceof Error?e.message:"No se pudo guardar el cliente"};}
}
export async function eliminarClienteAction(id:string):Promise<ActionResult>{try{await requireAuthRoles(GESTION_CLIENTES);const c=await prisma.cliente.findUnique({where:{id},include:{_count:{select:{pedidos:true,movimientosCuenta:true}}}});if(!c)return{success:false,error:"Cliente no encontrado"};if(c._count.pedidos||c._count.movimientosCuenta)return{success:false,error:"El cliente tiene historial y no puede eliminarse"};await prisma.cliente.delete({where:{id}});refresh();return{success:true,message:"Cliente eliminado"};}catch(e){return{success:false,error:e instanceof Error?e.message:"No se pudo eliminar"};}}
export async function guardarProveedorAction(id:string|null,data:ProveedorInput):Promise<ActionResult>{try{await requireAuthRoles(SOLO_ADMIN);const p=proveedorSchema.safeParse(data);if(!p.success)return{success:false,error:p.error.issues[0]?.message};const payload={...p.data,email:nullable(p.data.email),telefono:nullable(p.data.telefono),contacto:nullable(p.data.contacto),direccion:nullable(p.data.direccion),categoria:nullable(p.data.categoria)};if(id)await prisma.proveedor.update({where:{id},data:payload});else await prisma.proveedor.create({data:payload});refresh();return{success:true,message:id?"Proveedor actualizado":"Proveedor creado"};}catch(e){return{success:false,error:e instanceof Error?e.message:"No se pudo guardar"};}}
export async function eliminarProveedorAction(id:string):Promise<ActionResult>{try{await requireAuthRoles(SOLO_ADMIN);const p=await prisma.proveedor.findUnique({where:{id},include:{_count:{select:{gastos:true,movimientosCuenta:true}}}});if(!p)return{success:false,error:"Proveedor no encontrado"};if(p._count.gastos||p._count.movimientosCuenta)return{success:false,error:"El proveedor tiene historial y no puede eliminarse"};await prisma.proveedor.delete({where:{id}});refresh();return{success:true,message:"Proveedor eliminado"};}catch(e){return{success:false,error:e instanceof Error?e.message:"No se pudo eliminar"};}}

export async function registrarMovimientoCuentaAction(entidad:"CLIENTE"|"PROVEEDOR",data:MovimientoCuentaInput):Promise<ActionResult>{try{await requireAuthRoles(entidad === "CLIENTE" ? GESTION_CLIENTES : SOLO_ADMIN);const p=movimientoCuentaSchema.safeParse(data);if(!p.success)return{success:false,error:p.error.issues[0]?.message};const delta=p.data.tipo===TipoMovimientoCuenta.ABONO?-p.data.monto:p.data.monto;await prisma.$transaction(async tx=>{if(entidad==="CLIENTE"){await tx.movimientoCuentaCliente.create({data:{clienteId:p.data.entidadId,tipo:p.data.tipo,monto:money(p.data.monto),concepto:p.data.concepto}});await tx.cliente.update({where:{id:p.data.entidadId},data:{saldoCuentaCorriente:{increment:money(delta)}}});}else{await tx.movimientoCuentaProveedor.create({data:{proveedorId:p.data.entidadId,tipo:p.data.tipo,monto:money(p.data.monto),concepto:p.data.concepto}});await tx.proveedor.update({where:{id:p.data.entidadId},data:{saldoCuentaCorriente:{increment:money(delta)}}});}});refresh();return{success:true,message:"Movimiento registrado"};}catch(e){return{success:false,error:e instanceof Error?e.message:"No se pudo registrar"};}}

export async function crearCategoriaGastoAction(nombre:string):Promise<ActionResult>{try{await requireAuthRoles(SOLO_ADMIN);const p=categoriaGastoSchema.safeParse({nombre});if(!p.success)return{success:false,error:p.error.issues[0]?.message};await prisma.categoriaGasto.create({data:p.data});refresh();return{success:true,message:"Categoría creada"};}catch(e){return{success:false,error:e instanceof Error?e.message:"No se pudo crear"};}}
export async function guardarGastoAction(id:string|null,data:GastoInput):Promise<ActionResult>{try{await requireAuthRoles(SOLO_ADMIN);const p=gastoSchema.safeParse(data);if(!p.success)return{success:false,error:p.error.issues[0]?.message};const payload={categoriaId:p.data.categoriaId,proveedorId:p.data.proveedorId||null,descripcion:p.data.descripcion,monto:money(p.data.monto),fecha:new Date(p.data.fecha),pagado:p.data.pagado,fechaVencimiento:p.data.fechaVencimiento?new Date(p.data.fechaVencimiento):null};if(id)await prisma.gasto.update({where:{id},data:payload});else await prisma.gasto.create({data:payload});refresh();return{success:true,message:id?"Gasto actualizado":"Gasto registrado"};}catch(e){return{success:false,error:e instanceof Error?e.message:"No se pudo guardar el gasto"};}}
export async function eliminarGastoAction(id:string):Promise<ActionResult>{try{await requireAuthRoles(SOLO_ADMIN);await prisma.gasto.delete({where:{id}});refresh();return{success:true,message:"Gasto eliminado"};}catch(e){return{success:false,error:e instanceof Error?e.message:"No se pudo eliminar"};}}

type FilaImportada=Record<string,string|number|boolean|null|undefined>;
export async function importarEntidadesAction(tipo:"CLIENTES"|"PROVEEDORES",filas:FilaImportada[]):Promise<ActionResult<{importados:number;errores:number}>>{try{await requireAuthRoles(tipo === "CLIENTES" ? GESTION_CLIENTES : SOLO_ADMIN);if(filas.length>1000)return{success:false,error:"Máximo 1000 filas por archivo"};let importados=0,errores=0;for(const fila of filas){try{const nombre=String(fila.nombre??fila.Nombre??"").trim();if(!nombre){errores++;continue;}if(tipo==="CLIENTES"){const parsed=clienteSchema.safeParse({nombre,email:String(fila.email??fila.Email??""),telefono:String(fila.telefono??fila.Telefono??""),documento:String(fila.documento??fila.Documento??""),direccion:String(fila.direccion??fila.Direccion??""),descuentoFijo:Number(fila.descuentoFijo??fila.Descuento??0)});if(!parsed.success){errores++;continue;}const where=parsed.data.documento?{documento:parsed.data.documento}:parsed.data.email?{email:parsed.data.email}:null;if(where){const existing=await prisma.cliente.findFirst({where});if(existing){await prisma.cliente.update({where:{id:existing.id},data:{...parsed.data,email:nullable(parsed.data.email),documento:nullable(parsed.data.documento)}});}else await prisma.cliente.create({data:{...parsed.data,email:nullable(parsed.data.email),documento:nullable(parsed.data.documento)}});}else await prisma.cliente.create({data:parsed.data});}else{const parsed=proveedorSchema.safeParse({nombre,email:String(fila.email??fila.Email??""),telefono:String(fila.telefono??fila.Telefono??""),contacto:String(fila.contacto??fila.Contacto??""),direccion:String(fila.direccion??fila.Direccion??""),categoria:String(fila.categoria??fila.Categoria??"")});if(!parsed.success){errores++;continue;}const existing=parsed.data.email?await prisma.proveedor.findFirst({where:{email:parsed.data.email}}):null;if(existing)await prisma.proveedor.update({where:{id:existing.id},data:{...parsed.data,email:nullable(parsed.data.email)}});else await prisma.proveedor.create({data:{...parsed.data,email:nullable(parsed.data.email)}});}importados++;}catch{errores++;}}refresh();return{success:true,message:`${importados} filas importadas; ${errores} rechazadas`,data:{importados,errores}};}catch(e){return{success:false,error:e instanceof Error?e.message:"No se pudo importar"};}}
