"use client";
/* eslint-disable @next/next/no-img-element -- Las URLs de catálogo pueden pertenecer a proveedores dinámicos. */

import { useMemo, useState, useTransition } from "react";
import { useRouter } from "next/navigation";
import { ChefHat, Minus, Plus, Search, ShoppingBag, Store, Truck, Utensils } from "lucide-react";
import { crearPedidoPublicoAction } from "@/features/carta-qr/actions";
import { useCarritoPublico } from "@/stores/carrito-publico";

type Platillo = { id:string; nombre:string; descripcion:string|null; precio:number; imagenUrl:string|null; categoriaId:string };
type Categoria = { id:string; nombre:string; platillos:Platillo[] };
type Mesa = { id:string; numero:string; sala:{nombre:string} };

export function CartaPublica({ categorias, mesas, mesaInicial, restaurante }: { categorias:Categoria[]; mesas:Mesa[]; mesaInicial?:string; restaurante:string }) {
  const router=useRouter(); const {items,agregar,cambiar,limpiar}=useCarritoPublico(); const [categoria,setCategoria]=useState(categorias[0]?.id??""); const [busqueda,setBusqueda]=useState(""); const [carrito,setCarrito]=useState(false); const [pending,startTransition]=useTransition(); const [error,setError]=useState("");
  const [modalidad,setModalidad]=useState<"MESA"|"DELIVERY"|"RETIRO">(mesaInicial?"MESA":"RETIRO"); const [mesaId,setMesaId]=useState(mesaInicial??""); const [nombre,setNombre]=useState(""); const [telefono,setTelefono]=useState(""); const [direccion,setDireccion]=useState(""); const [referencia,setReferencia]=useState("");
  const productos=useMemo(()=>categorias.flatMap(c=>c.platillos).filter(p=>(!categoria||p.categoriaId===categoria)&&p.nombre.toLowerCase().includes(busqueda.toLowerCase())),[categorias,categoria,busqueda]); const total=items.reduce((s,i)=>s+i.precio*i.cantidad,0)+(modalidad==="DELIVERY"?5000:0); const cantidad=items.reduce((s,i)=>s+i.cantidad,0);
  const confirmar=()=>startTransition(async()=>{setError("");try {const r=await crearPedidoPublicoAction({solicitudId:useCarritoPublico.getState().prepararSolicitud(),modalidad,mesaId:mesaId||undefined,nombre,telefono,direccion,referencia,items:items.map(i=>({platilloId:i.platilloId,cantidad:i.cantidad}))});if(!r.success){setError(r.error);return;}limpiar();router.push(`/carta/seguimiento/${r.data.token}`);} catch {setError("No se pudo confirmar. Intenta de nuevo para recuperar tu pedido.");}});
  return <main className="min-h-screen bg-[#fffaf1] text-[#1D3557] pb-28">
    <header className="sticky top-0 z-20 bg-[#fffaf1]/95 backdrop-blur border-b border-orange-100"><div className="max-w-6xl mx-auto px-4 py-4 flex items-center"><div className="w-10 h-10 bg-[#E63946] text-white rounded-full flex items-center justify-center"><ChefHat/></div><div className="ml-3"><p className="font-black leading-tight">{restaurante}</p><p className="text-[10px] uppercase tracking-[.2em] text-[#E63946]">Carta digital</p></div><button onClick={()=>setCarrito(true)} className="ml-auto relative p-3 bg-[#1D3557] text-white rounded-full"><ShoppingBag className="w-5 h-5"/>{cantidad>0&&<b className="absolute -top-1 -right-1 bg-[#E63946] rounded-full text-[10px] w-5 h-5 grid place-items-center">{cantidad}</b>}</button></div></header>
    <section className="max-w-6xl mx-auto px-4 pt-8"><div className="max-w-2xl"><p className="text-xs font-black uppercase tracking-[.2em] text-[#E63946]">Hecho al momento</p><h1 className="text-4xl md:text-6xl font-black tracking-tight mt-2">Tu mesa. Tu antojo.<br/><span className="text-[#E63946]">Sin esperar.</span></h1><p className="mt-3 text-slate-500">Pide desde la mesa, para recoger o recibe en casa.</p></div><div className="mt-7 flex gap-3 overflow-x-auto pb-2">{categorias.map(c=><button key={c.id} onClick={()=>setCategoria(c.id)} className={`whitespace-nowrap px-4 py-2 rounded-full text-sm font-bold transition ${categoria===c.id?"bg-[#1D3557] text-white":"bg-white border border-orange-100"}`}>{c.nombre}</button>)}</div><label className="mt-4 max-w-md flex items-center bg-white border border-orange-100 rounded-2xl px-4"><Search className="w-4 h-4 text-slate-400"/><input value={busqueda} onChange={e=>setBusqueda(e.target.value)} placeholder="Buscar en la carta" className="w-full bg-transparent p-3 outline-none"/></label>
    <div className="grid sm:grid-cols-2 lg:grid-cols-3 gap-x-7 gap-y-8 mt-8">{productos.map(p=><article key={p.id} className="group"><div className="aspect-[4/3] rounded-[1.75rem] overflow-hidden bg-[#F4A261]/20 relative">{p.imagenUrl?<img src={p.imagenUrl} alt={p.nombre} className="w-full h-full object-cover group-hover:scale-105 transition duration-500"/>:<div className="h-full grid place-items-center text-[#E63946]"><Utensils className="w-14 h-14"/></div>}<button onClick={()=>agregar({platilloId:p.id,nombre:p.nombre,precio:p.precio})} className="absolute bottom-3 right-3 w-11 h-11 rounded-full bg-[#E63946] text-white grid place-items-center shadow-lg"><Plus/></button></div><div className="pt-3 flex gap-3"><div><h2 className="font-black text-lg">{p.nombre}</h2><p className="text-sm text-slate-500 line-clamp-2">{p.descripcion}</p></div><b className="ml-auto whitespace-nowrap">$ {Math.round(p.precio).toLocaleString("es-CO")}</b></div></article>)}</div></section>
    {carrito&&<div className="fixed inset-0 z-40 bg-slate-950/45 flex justify-end" onClick={()=>setCarrito(false)}><aside className="w-full max-w-md h-full bg-white p-5 overflow-y-auto" onClick={e=>e.stopPropagation()}><div className="flex items-center"><h2 className="text-2xl font-black">Tu pedido</h2><button onClick={()=>setCarrito(false)} className="ml-auto text-sm font-bold">Cerrar</button></div><div className="grid grid-cols-3 gap-2 mt-5">{([["MESA",Utensils,"Mesa"],["RETIRO",Store,"Retiro"],["DELIVERY",Truck,"Domicilio"]] as const).map(([id,Icon,label])=><button key={id} onClick={()=>setModalidad(id)} className={`p-3 rounded-2xl border text-xs font-bold ${modalidad===id?"bg-[#1D3557] text-white":""}`}><Icon className="w-5 h-5 mx-auto mb-1"/>{label}</button>)}</div><div className="divide-y mt-5">{items.map(i=><div key={i.platilloId} className="py-3 flex items-center"><div><b>{i.nombre}</b><p className="text-xs text-slate-500">$ {Math.round(i.precio*i.cantidad).toLocaleString("es-CO")}</p></div><div className="ml-auto flex items-center gap-3"><button onClick={()=>cambiar(i.platilloId,i.cantidad-1)}><Minus className="w-4 h-4"/></button><b>{i.cantidad}</b><button onClick={()=>cambiar(i.platilloId,i.cantidad+1)}><Plus className="w-4 h-4"/></button></div></div>)}</div>
      <div className="space-y-3 mt-5"><input value={nombre} onChange={e=>setNombre(e.target.value)} placeholder="Tu nombre" className="w-full p-3 border rounded-xl"/><input value={telefono} onChange={e=>setTelefono(e.target.value)} placeholder="Teléfono" className="w-full p-3 border rounded-xl"/>{modalidad==="MESA"&&<select value={mesaId} onChange={e=>setMesaId(e.target.value)} className="w-full p-3 border rounded-xl"><option value="">Selecciona mesa</option>{mesas.map(m=><option key={m.id} value={m.id}>{m.sala.nombre} · Mesa {m.numero}</option>)}</select>}{modalidad==="DELIVERY"&&<><input value={direccion} onChange={e=>setDireccion(e.target.value)} placeholder="Dirección de entrega" className="w-full p-3 border rounded-xl"/><input value={referencia} onChange={e=>setReferencia(e.target.value)} placeholder="Referencia" className="w-full p-3 border rounded-xl"/></>}</div>{error&&<p className="mt-3 text-sm font-bold text-rose-600">{error}</p>}<div className="mt-6 flex justify-between text-xl font-black"><span>Total</span><span>$ {Math.round(total).toLocaleString("es-CO")}</span></div><button disabled={pending||!items.length} onClick={confirmar} className="w-full mt-4 p-4 bg-[#E63946] text-white rounded-2xl font-black disabled:opacity-50">{pending?"Enviando…":"Confirmar pedido"}</button></aside></div>}
  </main>;
}
